# ─────────────────────────────────────────────
# Aggiungere in coda a /etc/dhcpcd.conf
# IP statico su wlan0 per l'access point
# ─────────────────────────────────────────────

interface wlan0
    static ip_address=192.168.73.1/24
    nohook wpa_supplicant
